security:
    encoders:
        App\Entity\Usertodo:
            algorithm: bcrypt

    providers:
        in_memory: { memory: ~ }

        doctrine:
            entity:
                class: App\Entity\Usertodo
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

            lazy: true

            pattern: ^/

            provider: doctrine

            form_login:
                login_path: login
                check_path: login

                always_use_default_target_path:  true

                default_target_path:  /
            
            logout:
                path: logout
                target: login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }